//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadastroWindownsForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        public int FuncionarioId { get; set; }
        public string FuncionarioNome { get; set; }
        public Nullable<int> FuncionarioIdade { get; set; }
        public string FuncionarioFuncao { get; set; }
        public Nullable<decimal> FuncionarioSalario { get; set; }
        public string FuncionarioCidade { get; set; }
        public string FuncionarioEndereco { get; set; }
        public string FuncionarioBairro { get; set; }
    }
}
